import { z } from 'zod';
export const createPlayerProfileZodSchema = z.object({
  body: z.object({
    fullName: z.string().min(2, 'Full name must be at least 2 characters'),
    position: z.string().min(1, 'Primary position is required'),
    secondaryPositions: z.array(z.string()).optional(),
    age: z.number().min(5).max(50),
    dateOfBirth: z.string().or(z.date()),
    country: z.string().min(2),
    dualNationality: z.string().optional(),
    currentClub: z.string().optional(),
    contractUntil: z.string().or(z.date()).optional(),
    marketValue: z.number().optional(),
    height: z.number().optional(),
    weight: z.number().optional(),
    preferredFoot: z.enum(['RIGHT', 'LEFT', 'BOTH']).optional(),
  }),
});

export const updatePlayerProfileZodSchema = z.object({
  body: z.object({
    fullName: z.string().optional(),
    position: z.string().optional(),
    secondaryPositions: z.array(z.string()).optional(),
    age: z.number().optional(),
    dateOfBirth: z.string().or(z.date()).optional(),
    country: z.string().optional(),
    dualNationality: z.string().optional(),
    currentClub: z.string().optional(),
    contractUntil: z.string().or(z.date()).optional(),
    marketValue: z.number().optional(),
    height: z.number().optional(),
    weight: z.number().optional(),
    preferredFoot: z.enum(['RIGHT', 'LEFT', 'BOTH']).optional(),
  }),
});

export const updatePlayerAttributesZodSchema = z.object({
  body: z.object({
    ballControl: z.number().min(1).max(99).optional(),
    dribbling: z.number().min(1).max(99).optional(),
    shortPassing: z.number().min(1).max(99).optional(),
    longPassing: z.number().min(1).max(99).optional(),
    crossing: z.number().min(1).max(99).optional(),
    shooting: z.number().min(1).max(99).optional(),
    finishing: z.number().min(1).max(99).optional(),
    longShots: z.number().min(1).max(99).optional(),
    firstTouch: z.number().min(1).max(99).optional(),
    positioning: z.number().min(1).max(99).optional(),
    vision: z.number().min(1).max(99).optional(),
    anticipation: z.number().min(1).max(99).optional(),
    composure: z.number().min(1).max(99).optional(),
    teamwork: z.number().min(1).max(99).optional(),
    workRate: z.number().min(1).max(99).optional(),
    decisions: z.number().min(1).max(99).optional(),
    attPosition: z.number().min(1).max(99).optional(),
    acceleration: z.number().min(1).max(99).optional(),
    sprintSpeed: z.number().min(1).max(99).optional(),
    stamina: z.number().min(1).max(99).optional(),
    strength: z.number().min(1).max(99).optional(),
    balance: z.number().min(1).max(99).optional(),
    agility: z.number().min(1).max(99).optional(),
    reactions: z.number().min(1).max(99).optional(),
    jumping: z.number().min(1).max(99).optional(),
    aggression: z.number().min(1).max(99).optional(),
    interceptions: z.number().min(1).max(99).optional(),
    marking: z.number().min(1).max(99).optional(),
    leadership: z.number().min(1).max(99).optional(),
    bravery: z.number().min(1).max(99).optional(),
    determination: z.number().min(1).max(99).optional(),
    heading: z.number().min(1).max(99).optional(),
    influence: z.number().min(1).max(99).optional(),
    tackling: z.number().min(1).max(99).optional(),
    offTheBall: z.number().min(1).max(99).optional(),
    oneOnOneFinishing: z.number().min(1).max(99).optional(),
    aerialAbility: z.number().min(1).max(99).optional(),
    shotAccuracy: z.number().min(1).max(99).optional(),
    reflexes: z.number().min(1).max(99).optional(),
    handling: z.number().min(1).max(99).optional(),
    oneOnOne: z.number().min(1).max(99).optional(),
    crossClaiming: z.number().min(1).max(99).optional(),
    shotStopping: z.number().min(1).max(99).optional(),
    footwork: z.number().min(1).max(99).optional(),
    distribution: z.number().min(1).max(99).optional(),
    communication: z.number().min(1).max(99).optional(),
    defensiveAwareness: z.number().min(1).max(99).optional(),
    throughPassing: z.number().min(1).max(99).optional(),
    creativity: z.number().min(1).max(99).optional(),
    chanceCreation: z.number().min(1).max(99).optional(),
    linkUpPlay: z.number().min(1).max(99).optional(),
    awareness: z.number().min(1).max(99).optional(),
  }),
});

export const createMatchRecordZodSchema = z.object({
  body: z.object({
    playerId: z.string().optional(),
    matchDate: z.string().or(z.date()),
    leagueType: z.string().min(1),
    homeTeam: z.string().min(1),
    awayTeam: z.string().min(1),
    homeScore: z.number().min(0),
    awayScore: z.number().min(0),
    result: z.enum(['W', 'D', 'L']),
    location: z.string().optional(),
    playerRating: z.number().min(0).max(100).optional(),
    goals: z.number().optional(),
    assists: z.number().optional(),
    passes: z.number().optional(),
    minutesPlayed: z.number().optional(),
    events: z
      .array(
        z.object({
          eventId: z.string(),
          count: z.number().min(0),
        }),
      )
      .optional(),
  }),
});
